# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = ../../ops.o
LINKOBJ  = ../../ops.o
LIBS     = -L"D:/eazyx/DevCpp511/MinGW64/lib" -L"D:/eazyx/DevCpp511/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -leasyx -g3
INCS     = -I"D:/eazyx/DevCpp511/MinGW64/include" -I"D:/eazyx/DevCpp511/MinGW64/x86_64-w64-mingw32/include" -I"D:/eazyx/DevCpp511/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/eazyx/DevCpp511/MinGW64/include" -I"D:/eazyx/DevCpp511/MinGW64/x86_64-w64-mingw32/include" -I"D:/eazyx/DevCpp511/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/eazyx/DevCpp511/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project_ball.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../../ops.o: ../../ops.cpp
	$(CPP) -c ../../ops.cpp -o ../../ops.o $(CXXFLAGS)
